[build]
  command = "python3 tools/gen-cover-thumbs.py || true && python3 tools/gen-gallery-thumbs.py || true && node build.js"
  publish = "."

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true
